# Generated by Django 5.2.9 on 2025-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(help_text='ID курса из Course Service')),
                ('user_id', models.IntegerField(help_text='ID пользователя из User Service')),
                ('rating', models.IntegerField(help_text='Рейтинг от 1 до 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('course_id', 'user_id')},
            },
        ),
    ]
