# Generated by Django 6.0 on 2025-12-17 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, help_text='ID пользователя из User Service')),
                ('course_id', models.IntegerField(db_index=True, help_text='ID курса из Course Service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена покупки', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['user_id', 'course_id'], name='purchases_user_id_88a406_idx'), models.Index(fields=['status'], name='purchases_status_12ed65_idx')],
                'unique_together': {('user_id', 'course_id')},
            },
        ),
    ]
