# Generated by Django 5.2.9 on 2025-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Mathematics', 'Mathematics'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='beginner', max_length=50),
        ),
    ]
